### ISSUE TITLE
Is it okay to use for components in production?

### ISSUE THREAD

**Issue by koresar** [ember-cli/ember-cli-htmlbars-inline-precompile#26]
Hello there.

Thank you for the amazing plugin!

I found this site demonstrates how to use the module for components: http://www.ember-redux.com/
What are the pros and cons of doing that for production code?
Please note, I'm not asking about tests, but about components themselves.

Cheers

**Comment by pangratz** [comment]
Hey @koresar,
thanks for the kind words!

Until I saw `ember-redux` I have never thought about using this plugin directly within a component :smile: It's an interesting idea!

I can think of the following downsides at the moment:

I don't know the specific details of `HTMLBars` compilation within `ember build --prod`, but maybe the template compilation in a production environment does some extra optimization and debug-code-stripping. Something like this would currently not be handled by `ember-cli-htmlbars-inline-precompile`.

Also - not sure how likely - but there might be some effects when the template is included in the JavaScript file directly, since it gets transpiled via `Babel` from `ES6` to `ES5`. The functionality of the compiled template function should stay the same, but maybe it's not ideal in terms of code minimization.

That being said, I think there is some more investigation needed to my above statements, if they are really an issue. Chances are that they aren't and using the plugin directly within JS is a valid use case.

I will leave this issue open so future findings can be reported here.

Cheers.

**Comment by rwjblue** [comment]
Yes, should work fine.

**Comment by koresar** [comment]
Thanks @rwjblue. I appreciate. 

What are the pros and cons of doing that for production code? Anything from the top of the head?
