### ISSUE TITLE
Cannot read property 'lt' of undefined

### ISSUE THREAD

**Issue by brianhjelle** [ember-cli/ember-cli-htmlbars-inline-precompile#74]
I tried running 'ember new' but it was not successful.  I am using Windows 7, Node 6.10.1, and ember-cli 2.12.1.  The error was "Cannot read property 'lt' of undefined".

**Comment by kfoisy** [comment]
I just started seeing some of my builds fail with this error as well. It appears to be due to the `lt` reference on this commit: https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/commit/d82e88aea19e619a951768cad825d3e742288e0e#diff-168726dbe96b3ce427e7fedce31bb0bcR18

**Comment by rwjblue** [comment]
Can you tell me what the results of `npm ls ember-cli-htmlbars-inline-precompile` are?

I suspect you got v0.3.7 which was broken and fixed with https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/commit/12f146c8aae8ff0259c06f4d77281ba95af54645 (and released as v0.3.8 a few minutes after publishing 0.3.7).

**Comment by brianhjelle** [comment]
When I run `npm ls ember-cli-htmlbars-inline-precompile` I get _-- (empty) npm ERR!     1_

**Comment by brianhjelle** [comment]
I just tried `ember new` again and it worked without any errors.  As you said, I think it just took a little bit of time for v0.3.8 to get pulled in.

**Comment by rwjblue** [comment]
OK, great! Sorry you got bit by my mistake (and the lack of good test coverage for that part of this addon).

**Comment by brianhjelle** [comment]
Thank you for your help and quick responses!
